Parameters:
  EC2AccessKey:
    Description: SSH key
    Type: "AWS::EC2::KeyPair::KeyName"

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lohich
      AccessControl: Private

  AppHost:
    DependsOn:
      - ClouformationUser
      - SecurityGroup
      - SSHSecurityGroup
      - dynamodbTable
      - sqsQueue
      - CodeDeployInstanceProfile
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0f4bbc925efd23616"
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroup
        - !Ref SSHSecurityGroup
      KeyName: !Ref EC2AccessKey
      Tags:
        - Key: Name
          Value: AppHost
      IamInstanceProfile: !Ref CodeDeployInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          sudo yum update
          sudo yum install ruby
          sudo yum install wget
          cd /home/ec2-user
          wget https://aws-codedeploy-eu-central-1.s3.eu-central-1.amazonaws.com/latest/install
          chmod +x ./install
          sudo ./install auto
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: dotnet port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "ISBN"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ISBN"
          KeyType: "HASH"
      TableName: "books"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  sqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: Books

  QueueReader:
    DependsOn:
      - sqsQueue
      - s3Bucket
      - LambdaRole
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "QueueReader"
      Handler: AWSLambda1::AWSLambda1.Function::FunctionHandler
      Role:
        Fn::GetAtt:
          - "LambdaRole"
          - "Arn"
      Runtime: dotnetcore2.1
      Code:
        S3Bucket: lohichwow
        S3Key: lambda.zip
      MemorySize: 512
      Timeout: 15
  LambdaTrigger:
    DependsOn:
      - QueueReader
      - sqsQueue
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - "sqsQueue"
          - "Arn"
      FunctionName:
        Fn::GetAtt:
          - "QueueReader"
          - "Arn"

  CodeDeploy:
    Type: "AWS::CodeDeploy::Application"
    Properties:
      ApplicationName: Books
  DeploymentGroup:
    DependsOn:
      - CodeDeploy
      - CodeDeplpoyRole
      - AppHost
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      ApplicationName: !Ref CodeDeploy
      ServiceRoleArn: !GetAtt CodeDeplpoyRole.Arn
      DeploymentGroupName: AppHosts
      Ec2TagFilters:
        - Key: Name
          Value: AppHost
          Type: KEY_AND_VALUE

  ClouformationUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
      UserName: AppUser
  AppAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ClouformationUser

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"
  CodeDeplpoyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codedeploy.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
  CodeDeployInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"

  LambdaExcecutionPolicy:
    DependsOn:
      - "LambdaRole"
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "LambdaExecutionPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:*"
            Resource:
              - "arn:aws:logs:*:*:*"
      Roles:
        - !Ref LambdaRole
  CodeDeployPolicy:
    DependsOn:
      - CodeDeployInstanceRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "CodeDeployEC2Permisions"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:Get*"
              - "s3:List*"
            Resource:
              - "*"
      Roles:
        - !Ref CodeDeployInstanceRole

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  CodeDeployInstanceProfile:
    DependsOn:
      - CodeDeployInstanceRole
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref CodeDeployInstanceRole
