name: Build & Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - uses: chrislennon/action-aws-cli@v1.1
    - name: Build
      run: aws codebuild start-build --project-name Books

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - uses: chrislennon/action-aws-cli@v1.1
    - name: Deploy
      run: aws deploy create-deployment --application-name Books --s3-location bucket=lohich,key=Books,bundleType=zip --deployment-group-name First
